### ISSUE TITLE
Error occurred during loading data.

### ISSUE THREAD

**Issue by Jlucu4ka228** [Lucky1376/ORION-Bomber#1]
Здравствуйте. Использую Ваш бомбер на GNU/Linux, установил все зависимости через pip install -r requirements.txt
Он спросил номер телефона, я ввёл и нажал начать спам.
Чуть-чуть подумав, он выплюнул:
```
Остановка спама
├Termux: На встроенной клавиатуре от Termux выбрать CTRL затем C
└Windows: Комбинация клавишь Ctrl+C или Ctrl+Z

Подпишитесь на наш Телеграм! t.me/orion_bomber

Error occurred during loading data. Trying to use cache server file https://useragent.melroy.org/cache.json
Traceback (most recent call last):
  File "/home/leca/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 64, in get
    urlopen(
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leca/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 139, in load
    browsers_dict[browser_name] = get_browser_user_agents(
  File "/home/leca/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 100, in get_browser_user_agents
    html = get(
  File "/home/leca/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 87, in get
    raise FakeUserAgentError("Maximum amount of retries reached")
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached


Из-за неизвестной ошибки наша программа выдала ошибку при спаме

Данная ошибка была сохранена в логи
Пожалуйста отправьте нам файл с логами по инструкции в главном меню чтобы мы могли улучшать наш проект с вашей помощью

Нажмите Enter чтобы вернуть назад
```
Не могу отправить лог, так как запускаю бомбер на GNU/Linux и директорий, связанных с термуксом у меня нет. 
На прошлых версиях бомбер работал. Спасибо

**Comment by Lucky1376** [comment]
Здравствуйте!

Начнем с того что наш бомбер изначально не создавался с поддержкой Linux, как написано в README наш бомбер имеет поддержку на Windows предположительно начиная с 7 версии и поддержку на Android в приложении Termux.
Termux это лишь симуляция консоли Linux и поэтому многие команды работают и на самом Linux включая определение ОС, но директории у Android и Linux разные и поэтому могут срабатывать многие ошибки.

Также по вашему вопросу мы определили нашу глобальную ошибку которая у многих вызывалась и с вами мы поняли в чем проблема, есть предположения что именно из-за нее у вас не работает бомбер. Ожидайте патч новой версии в ближайшие дни и после попробуйте снова запустить на Linux, но мы не гарантируем что у вас все гладко запуститься. Спасибо вам!
